
package com.isg.de.ws.server.soap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "NativeEventProviderSOAPWS", targetNamespace = "http://soap.server.ws.de.isg.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface NativeEventProviderSOAPWS {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUpdatedNativeEventsJSON", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetUpdatedNativeEventsJSON")
    @ResponseWrapper(localName = "getUpdatedNativeEventsJSONResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetUpdatedNativeEventsJSONResponse")
    public String getUpdatedNativeEventsJSON();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNativeActiveEventsJSON", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeActiveEventsJSON")
    @ResponseWrapper(localName = "getNativeActiveEventsJSONResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeActiveEventsJSONResponse")
    public String getNativeActiveEventsJSON();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGeoAllNativeEvents", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetGeoAllNativeEvents")
    @ResponseWrapper(localName = "getGeoAllNativeEventsResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetGeoAllNativeEventsResponse")
    public String getGeoAllNativeEvents();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNativeScheduleEventsJSON", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeScheduleEventsJSON")
    @ResponseWrapper(localName = "getNativeScheduleEventsJSONResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeScheduleEventsJSONResponse")
    public String getNativeScheduleEventsJSON();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGeoNativeActiveEvents", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetGeoNativeActiveEvents")
    @ResponseWrapper(localName = "getGeoNativeActiveEventsResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetGeoNativeActiveEventsResponse")
    public String getGeoNativeActiveEvents();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGeoNativeScheduleEvents", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetGeoNativeScheduleEvents")
    @ResponseWrapper(localName = "getGeoNativeScheduleEventsResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetGeoNativeScheduleEventsResponse")
    public String getGeoNativeScheduleEvents();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNativeScheduleEvents", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeScheduleEvents")
    @ResponseWrapper(localName = "getNativeScheduleEventsResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeScheduleEventsResponse")
    public String getNativeScheduleEvents();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllNativeEvents", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetAllNativeEvents")
    @ResponseWrapper(localName = "getAllNativeEventsResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetAllNativeEventsResponse")
    public String getAllNativeEvents();

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNativeActiveEvents", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeActiveEvents")
    @ResponseWrapper(localName = "getNativeActiveEventsResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeActiveEventsResponse")
    public String getNativeActiveEvents();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNativeEventsByState", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeEventsByState")
    @ResponseWrapper(localName = "getNativeEventsByStateResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeEventsByStateResponse")
    public String getNativeEventsByState(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNativeEventsByType", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeEventsByType")
    @ResponseWrapper(localName = "getNativeEventsByTypeResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeEventsByTypeResponse")
    public String getNativeEventsByType(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllNativeEventsJSON", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetAllNativeEventsJSON")
    @ResponseWrapper(localName = "getAllNativeEventsJSONResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetAllNativeEventsJSONResponse")
    public String getAllNativeEventsJSON();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGeoNativeEventsByType", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetGeoNativeEventsByType")
    @ResponseWrapper(localName = "getGeoNativeEventsByTypeResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetGeoNativeEventsByTypeResponse")
    public String getGeoNativeEventsByType(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNativeEventsByStateJSON", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeEventsByStateJSON")
    @ResponseWrapper(localName = "getNativeEventsByStateJSONResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeEventsByStateJSONResponse")
    public String getNativeEventsByStateJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUpdatedNativeEvents", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetUpdatedNativeEvents")
    @ResponseWrapper(localName = "getUpdatedNativeEventsResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetUpdatedNativeEventsResponse")
    public String getUpdatedNativeEvents();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGeoNativeEventsByState", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetGeoNativeEventsByState")
    @ResponseWrapper(localName = "getGeoNativeEventsByStateResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetGeoNativeEventsByStateResponse")
    public String getGeoNativeEventsByState(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNativeEventsByTypeJSON", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeEventsByTypeJSON")
    @ResponseWrapper(localName = "getNativeEventsByTypeJSONResponse", targetNamespace = "http://soap.server.ws.de.isg.com/", className = "com.isg.de.ws.server.soap.GetNativeEventsByTypeJSONResponse")
    public String getNativeEventsByTypeJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
