
package com.isg.de.ws.server.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "NativeEventProviderSOAPWSService", targetNamespace = "http://soap.server.ws.de.isg.com/", wsdlLocation = "https://data1.xcmdata.org/ISGDE/soap/NativeEventProvider?wsdl")
public class NativeEventProviderSOAPWSService
    extends Service
{

    private final static URL NATIVEEVENTPROVIDERSOAPWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException NATIVEEVENTPROVIDERSOAPWSSERVICE_EXCEPTION;
    private final static QName NATIVEEVENTPROVIDERSOAPWSSERVICE_QNAME = new QName("http://soap.server.ws.de.isg.com/", "NativeEventProviderSOAPWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://data1.xcmdata.org/ISGDE/soap/NativeEventProvider?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        NATIVEEVENTPROVIDERSOAPWSSERVICE_WSDL_LOCATION = url;
        NATIVEEVENTPROVIDERSOAPWSSERVICE_EXCEPTION = e;
    }

    public NativeEventProviderSOAPWSService() {
        super(__getWsdlLocation(), NATIVEEVENTPROVIDERSOAPWSSERVICE_QNAME);
    }

    public NativeEventProviderSOAPWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), NATIVEEVENTPROVIDERSOAPWSSERVICE_QNAME, features);
    }

    public NativeEventProviderSOAPWSService(URL wsdlLocation) {
        super(wsdlLocation, NATIVEEVENTPROVIDERSOAPWSSERVICE_QNAME);
    }

    public NativeEventProviderSOAPWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, NATIVEEVENTPROVIDERSOAPWSSERVICE_QNAME, features);
    }

    public NativeEventProviderSOAPWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NativeEventProviderSOAPWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns NativeEventProviderSOAPWS
     */
    @WebEndpoint(name = "NativeEventProviderSOAPWSPort")
    public NativeEventProviderSOAPWS getNativeEventProviderSOAPWSPort() {
        return super.getPort(new QName("http://soap.server.ws.de.isg.com/", "NativeEventProviderSOAPWSPort"), NativeEventProviderSOAPWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NativeEventProviderSOAPWS
     */
    @WebEndpoint(name = "NativeEventProviderSOAPWSPort")
    public NativeEventProviderSOAPWS getNativeEventProviderSOAPWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.server.ws.de.isg.com/", "NativeEventProviderSOAPWSPort"), NativeEventProviderSOAPWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (NATIVEEVENTPROVIDERSOAPWSSERVICE_EXCEPTION!= null) {
            throw NATIVEEVENTPROVIDERSOAPWSSERVICE_EXCEPTION;
        }
        return NATIVEEVENTPROVIDERSOAPWSSERVICE_WSDL_LOCATION;
    }

}
